INSERT INTO category (category_name) values ('American');
INSERT INTO category (category_name) values ('Italian');
INSERT INTO category (category_name) values ('Mexican');
INSERT INTO category (category_name) values ('Fast Food');
insert into unit_of_measure(description) values ('Cup');
insert into unit_of_measure(description) values ('Pinch');
insert into unit_of_measure(description) values ('Teaspoon');
insert into unit_of_measure(description) values ('Tablespoon');
insert into unit_of_measure(description) values ('Ounce');
insert into unit_of_measure(description) values ('Each');
insert into unit_of_measure(description) values ('Pint');
insert into unit_of_measure(description) values ('Dash');